# Generated by Django 4.1.7 on 2023-04-12 17:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='food_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('V', 'Vegetarian'), ('VG', 'Vegan'), ('NV', 'Non-Vegetarian')], default='V', max_length=2),
            preserve_default=False,
        ),
    ]
