# Generated by Django 4.1.7 on 2023-04-12 18:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_details', '0003_alter_restaurant_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='food_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('V', 'Vegetarian'), ('VG', 'Vegan'), ('NV', 'Non-Vegetarian')], max_length=10),
        ),
    ]
